spring:
  datasource:
    url: jdbc:mysql://mysql.edith.fun:32777/homeware
    password: D@rkS0u1!
    username: root
    driver-class-name: "com.mysql.jdbc.Driver"
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  redis:
    database: 0
    host: redis
    port: 6379
refreshTokenExpireTime: 86400
elasticsearch:
  host: es.mysql.fun
  port: 32781
  index_name: mylife
  doc_type: movie
  mapping: "{ \"properties\": { \"genres\": { \"type\": \"keyword\" }, \"regions\": { \"type\": \"keyword\" }, \"director\": { \"type\": \"text\",   \"fields\": { \"keyword\": { \"type\":  \"keyword\" } } }, \"playwright\":{ \"type\": \"text\",  \"fields\": { \"keyword\": { \"type\":  \"keyword\" } } }, \"cast\": { \"type\": \"text\",   \"fields\": { \"keyword\": { \"type\":  \"keyword\" } } }, \"post\": { \"type\": \"text\", \"index\": false }, \"douban_link\": { \"type\": \"text\", \"index\": false }, \"rating\": { \"type\": \"float\"}, \"name\": { \"type\": \"text\",   \"fields\": { \"keyword\": { \"type\":  \"keyword\" } } }, \"year\": { \"type\": \"short\"} } }"
