spring:
  datasource:
    url: jdbc:mysql://mysql:3306/homeware
    password: password
    username: root
    driver-class-name: "com.mysql.jdbc.Driver"
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  redis:
    database: 0
    host: redis
    port: 6379
refreshTokenExpireTime: 86400
